---
services:
- service_instance: config-service
  service: p-config-server
  plan: standard
  parameters_json: >
     {
        "count": 1,
        "git": {
            "password": "chandhu123",
            "uri": "https://github.com/ctatineni/configrepo",
            "username": "ctatineni"
        }
     }